env:
  - CI=true
language: node_js
node_js:
  - "9"
cache:
  directories:
  - node_modules
  - functions/node_modules
before_install:
  - yarn global add firebase-tools
install:
  - yarn install
  - cd functions
  - yarn install
  - cd ..
script:
  - CI=false yarn build
  - cd functions
  - CI=false yarn build
  - cd ..
  - echo "Deploying!"
  - yarn test
after_success:
  - firebase deploy -m "Travis deploy" --non-interactive --token $FIREBASE_TOKEN
branches:
  only:
    - master